#!/usr/bin/env bash

# ANSI color scheme script featuring PACMAN
# Author: pfh
# Source: http://crunchbang.org/forums/viewtopic.php?pid=144481#p144481 
# Initializing procedure by lolilolicon

	f=3 b=4
	for j in f b; do
	  for i in {0..7}; do
	    printf -v $j$i %b "\e[${!j}${i}m"
	  done
	done
	bld=$'\e[1m'
	rst=$'\e[0m'
	inv=$'\e[7m'

initializeANSI()
{
 esc=""

  blackf="${esc}[31m";   redf="${esc}[31m";    greenf="${esc}[32m"
  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
  cyanf="${esc}[36m";    whitef="${esc}[37m"

  blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
  cyanb="${esc}[46m";    whiteb="${esc}[47m"

  boldon="${esc}[1m";    boldoff="${esc}[22m"
  italicson="${esc}[3m"; italicsoff="${esc}[23m"
  ulon="${esc}[4m";      uloff="${esc}[24m"
  invon="${esc}[7m";     invoff="${esc}[27m"

  reset="${esc}[0m"
}


initializeANSI

cat << EOF
$rst
                                                          ${boldon}${blackf} ██████${reset}
                                                          ${boldon}${blackf}██${reset}██${reset}${bluef}██${reset}${boldon}${blackf}██${reset}${bluef}██${reset}
                                                          ${boldon}${blackf}██${reset}██${bluef}██${reset}${boldon}${blackf}██${reset}${bluef}██${reset}
                                                          ${boldon}${blackf}██████${reset}${purplef}██████${reset}
 $f3  ▄███████▄                $f1  ▄██████▄    $f6  ▄██████▄      ${boldon}${blackf}████${reset}████${boldon}${blackf}██${reset}
 $f3▄█████████▀▀               $f1▄$f7█▀█$f1██$f7█▀█$f1██▄  $f6▄██$f7█▀█$f6██$f7█▀█$f6▄  ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
 $f3███████▀      $f7▄▄  ▄▄  ▄▄   $f1█$f7▄▄█$f1██$f7▄▄█$f1███  $f6███$f7█▄▄$f6██$f7█▄▄$f6█  ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
 $f3███████▄      $f7▀▀  ▀▀  ▀▀   $f1████████████  $f6████████████  ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
 $f3▀█████████▄▄               $f1██▀██▀▀██▀██  $f6██▀██▀▀██▀██    ${boldon}${blackf}████${reset}████${boldon}${blackf}██${reset}
 $f3  ▀███████▀                $f1▀   ▀  ▀   ▀  $f6▀   ▀  ▀   ▀   ${boldon}${blackf}███${reset}${purplef}███   ████${reset}
$rst
EOF
